const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  BUSINESS: '/business',
  USERS: '/users',
  USER_DETAIL: '/users/:key',
  ROLES: '/roles',
  SERVICES: '/services',
  SERVICE_DETAIL: '/services/:key',
  CERTIFICATIONS: '/certifications',
  CUSTOMERS: '/customers',
  CUSTOMER_DETAIL: '/customers/:key',
  LOCATIONS: '/locations',
  LOCATION_DETAIL: '/locations/:key',
  FLEET: '/fleet',
  FLEET_DETAIL: '/fleet/:key',
  WORKORDERS: '/workorders',
  WORKORDER_DETAIL: '/workorders/:key',
  WORKTASKS: '/worktasks',
  WORKTASK_DETAIL: '/worktasks/:key',
  INVOICES: '/invoices',
  INVOICE_DETAIL: '/invoices/:key',
  SUBCONTRACTORS: '/subcontractors',
  AUDIT: '/audit',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  CREATE_BUSINESS: '/create-business',
  ADMIN_BUSINESSES: '/admin/businesses',
  ADMIN_BUSINESS_DETAIL: '/admin/businesses/:key',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: '/admin/users/:key',
  ADMIN_HEALTH: '/admin/health',
  ADMIN_DATA: '/admin/data',
}

export default ROUTES
